// GENERATED by scripts/build-token-registry.mjs from docs/rwa-registry.json (2026-10-10T11:32:01.776Z). Do not edit by hand.
// bStocks on BSC that quoted as a normal SWAP with no honeypot/tax flag, low price impact and no leverage.
// Being listed here does NOT make a token tradable: see VERIFIED_LIVE_SYMBOLS in token-registry.ts.

export interface RegistryRow {
  symbol: string;
  ticker: string;
  name: string;
  /** Lowercase. Comes from Binance RWA search, never guessed. */
  address: string;
  decimals: 18;
  /** Price impact of a 1 USDT quote when the registry was generated. */
  priceImpactPct: number;
}

export const REGISTRY_GENERATED_AT = "2026-10-10T11:32:01.776Z";

export const REGISTRY_ROWS: readonly RegistryRow[] = [
  { symbol: "AAPLB", ticker: "AAPL", name: "Apple Inc.", address: "0x431a3bee82e2ca41e49895cbece5bb0f76a89b7a", decimals: 18, priceImpactPct: 0.0005006122 },
  { symbol: "ADBEB", ticker: "ADBE", name: "Adobe", address: "0x65c0249d49e3231540fd0db0a1ae9259e6eaaf57", decimals: 18, priceImpactPct: 0 },
  { symbol: "AMATB", ticker: "AMAT", name: "Applied Materials, Inc.", address: "0xa304bd78e739c0f777202b3eb73ac3736d1df801", decimals: 18, priceImpactPct: 0 },
  { symbol: "AMCB", ticker: "AMC", name: "AMC Entertainment Holdings, Inc.", address: "0x96e7d606e229448ef817a7f35fd7394c3e15d00c", decimals: 18, priceImpactPct: 0.0025039149 },
  { symbol: "AMDB", ticker: "AMD", name: "Advanced Micro Devices", address: "0x75fd4cf6f8392e41e70391d60c90c0d5211603a1", decimals: 18, priceImpactPct: 0 },
  { symbol: "AMZNB", ticker: "AMZN", name: "Amazon.Com Inc", address: "0x1a4b499833a79a09ad7cf1d42d7dacf71e92eb00", decimals: 18, priceImpactPct: 0.0025002489 },
  { symbol: "ARMB", ticker: "ARM", name: "Arm Holdings plc", address: "0xd42a79ebb7f527f40faecd196ffb47ad5e8d6f8c", decimals: 18, priceImpactPct: 0 },
  { symbol: "ASMLB", ticker: "ASML", name: "ASML Holding NV", address: "0xfbfb4f79cfb4c34dcd7c82bdee5a0fa199b2e7f9", decimals: 18, priceImpactPct: 0 },
  { symbol: "ASTSB", ticker: "ASTS", name: "AST SpaceMobile, Inc.", address: "0x58b6f5feeb8436489f5bf4a56619092b1fa8e777", decimals: 18, priceImpactPct: 0 },
  { symbol: "AVGOB", ticker: "AVGO", name: "Broadcom Inc.", address: "0x76682c454467b3a1150ad8b6a92fc5ee2c21d7ed", decimals: 18, priceImpactPct: 0 },
  { symbol: "BABAB", ticker: "BABA", name: "Alibaba Group Holding Limited", address: "0x4ef9d3062c7f6eba4aae4990c5036598c6eff4ec", decimals: 18, priceImpactPct: 0.0005035572 },
  { symbol: "BEB", ticker: "BE", name: "Bloom Energy Corporation", address: "0x5519de00f5388c17d886b97cb5d2d43a812a82bc", decimals: 18, priceImpactPct: 0 },
  { symbol: "COINB", ticker: "COIN", name: "Coinbase Global, Inc.", address: "0x585bde7c54abb5ccd7791f923d6c2187635f3952", decimals: 18, priceImpactPct: 0.0006912344 },
  { symbol: "CRDOB", ticker: "CRDO", name: "Credo Technology Group Holding Ltd", address: "0x6e7d451f9d30327d32020f116fa79c23b24e9c8d", decimals: 18, priceImpactPct: 0 },
  { symbol: "CRMB", ticker: "CRM", name: "Salesforce, Inc.", address: "0x8c433eca1be0e2a357015602f63751c768f6f643", decimals: 18, priceImpactPct: 0 },
  { symbol: "CRWDB", ticker: "CRWD", name: "CrowdStrike Holdings, Inc.", address: "0x814981cf5df4a14d4d7328f9abf0d02e9ed54cd1", decimals: 18, priceImpactPct: 0 },
  { symbol: "CRWVB", ticker: "CRWV", name: "CoreWeave, Inc.", address: "0x33e7317e17838fee56b10fe8d0b9ca6ca3090c95", decimals: 18, priceImpactPct: 0 },
  { symbol: "CYPHB", ticker: "CYPH", name: "Cypherpunk Technologies Inc.", address: "0x0393c28065c54e48b45bdb05eff5c401cf891da1", decimals: 18, priceImpactPct: 0.0509878153 },
  { symbol: "DELLB", ticker: "DELL", name: "Dell Technologies Inc.", address: "0x0e7a51966c66648999d506e1372efdea1b78cb0b", decimals: 18, priceImpactPct: 0 },
  { symbol: "DJTB", ticker: "DJT", name: "Trump Media & Technology Group", address: "0xf2ec508422174ee564de98187db9359d318afb6b", decimals: 18, priceImpactPct: 0 },
  { symbol: "EWYB", ticker: "EWY", name: "iShares MSCI South Korea ETF", address: "0xbe82f76637dba2c114c41df856c2c51e522e2cb8", decimals: 18, priceImpactPct: 0 },
  { symbol: "FLNCB", ticker: "FLNC", name: "Fluence Energy, Inc.", address: "0x4af1d41cd9dd950dca43984b43aaa2a8702714ac", decimals: 18, priceImpactPct: 0 },
  { symbol: "FWDIB", ticker: "FWDI", name: "Forward Industries Inc", address: "0x83f1a739fae6517c4672c5e10c8ea918925eb584", decimals: 18, priceImpactPct: 0.0513730278 },
  { symbol: "GLWB", ticker: "GLW", name: "Corning Incorporated", address: "0x740e075cbbea22a082b9d6679e65e82767875b6a", decimals: 18, priceImpactPct: 0 },
  { symbol: "GMEB", ticker: "GME", name: "GameStop Corp.", address: "0x46ceefda28dd7207059ed19b0acdc026955bb15c", decimals: 18, priceImpactPct: 0.0033702928 },
  { symbol: "GOOGLB", ticker: "GOOGL", name: "Alphabet Inc.", address: "0x3f53de71c126bdabae20f9cd64848d317f6c3238", decimals: 18, priceImpactPct: 0.000393371 },
  { symbol: "GSB", ticker: "GS", name: "Goldman Sachs Group Inc.", address: "0x20cce6656e5f7f79f280e2d0f5db55b401bdbfce", decimals: 18, priceImpactPct: 0 },
  { symbol: "HIMSB", ticker: "HIMS", name: "Hims & Hers Health, Inc.", address: "0xee6f4bcc88c2c8583d5a65c7d0c877b464100711", decimals: 18, priceImpactPct: 0 },
  { symbol: "HOODB", ticker: "HOOD", name: "Robinhood Markets, Inc.", address: "0xa394dcea3fd3847fd793afbfd163e2e3858b7c65", decimals: 18, priceImpactPct: 0.0006952269 },
  { symbol: "IBMB", ticker: "IBM", name: "International Business Machines Corporation", address: "0xfa273b076feb8c0fb34e554ae341082323d016a3", decimals: 18, priceImpactPct: 0 },
  { symbol: "INTCB", ticker: "INTC", name: "Intel Corp", address: "0xe614e2fc6c787035ff51f452e8e826bfd32d5283", decimals: 18, priceImpactPct: 0 },
  { symbol: "JPMB", ticker: "JPM", name: "JPMorgan Chase & Co.", address: "0xbd49d695ba2cc46c8c603eb62afcd7fff4698281", decimals: 18, priceImpactPct: 0 },
  { symbol: "LITEB", ticker: "LITE", name: "Lumentum Holdings Inc.", address: "0x64748bea17b6d19e242adf20425de2440c656142", decimals: 18, priceImpactPct: 0 },
  { symbol: "LLYB", ticker: "LLY", name: "Eli Lilly & Co.", address: "0x5407912f1aa4b9e05cbe6abeb9721547a643ec6b", decimals: 18, priceImpactPct: 0 },
  { symbol: "METAB", ticker: "META", name: "Meta Platforms, Inc.", address: "0x7425889fe94f9d693e8daefe88bcced6acfef4c0", decimals: 18, priceImpactPct: 0 },
  { symbol: "MRVLB", ticker: "MRVL", name: "Marvell Technology, Inc.", address: "0x16cd4fe7e8880ecc3ba222795229e20489fc2c76", decimals: 18, priceImpactPct: 0 },
  { symbol: "MSFTB", ticker: "MSFT", name: "Microsoft Corp", address: "0x80106cb3ead06659a5ad19df39d9b4733863b9b0", decimals: 18, priceImpactPct: 0 },
  { symbol: "MSTRB", ticker: "MSTR", name: "Strategy Inc", address: "0xe87afb3076aeb0f9b14e368de8145ae6a2826a14", decimals: 18, priceImpactPct: 0.0030992993 },
  { symbol: "MUB", ticker: "MU", name: "Micron Technology, Inc.", address: "0xcdf2f3e0fa43c47a6662a91c9e4a7c5f69762699", decimals: 18, priceImpactPct: 0 },
  { symbol: "NBISB", ticker: "NBIS", name: "Nebius Group", address: "0xe256bc2a4f5297f8ba6f043f180a46300ecbcbb1", decimals: 18, priceImpactPct: 0.0029158734 },
  { symbol: "NFLXB", ticker: "NFLX", name: "NetFlix Inc", address: "0xd6829ea836b6fa224d099d40e54b31262f874631", decimals: 18, priceImpactPct: 0 },
  { symbol: "NVDAB", ticker: "NVDA", name: "Nvidia Corp", address: "0x02fca66c1d1afb4e2a7884261eb00f63598a7436", decimals: 18, priceImpactPct: 0 },
  { symbol: "ORCLB", ticker: "ORCL", name: "Oracle Corp", address: "0x4684d9887fc1c71cba7bab8e88835cec217eb598", decimals: 18, priceImpactPct: 0.0005586575 },
  { symbol: "PLTRB", ticker: "PLTR", name: "Palantir Technologies Inc.", address: "0x0ca5d51d0277bd006fd9607d3e560785ebad8222", decimals: 18, priceImpactPct: 0 },
  { symbol: "PYPLB", ticker: "PYPL", name: "PayPal Holdings, Inc.", address: "0x2806a561fc1f9259b2d54a281796bde0d92762ae", decimals: 18, priceImpactPct: 0 },
  { symbol: "QCOMB", ticker: "QCOM", name: "Qualcomm Inc", address: "0x5f7a56e877b9130608bf8be962621011182fefe1", decimals: 18, priceImpactPct: 0 },
  { symbol: "QQQB", ticker: "QQQ", name: "Invesco QQQ Trust", address: "0x205812cdbed920aff76c6580abd681a46d11efc7", decimals: 18, priceImpactPct: 0 },
  { symbol: "RDDTB", ticker: "RDDT", name: "Reddit, Inc.", address: "0x41622a9125a22767df8c1dc79fc17299bac4bd0b", decimals: 18, priceImpactPct: 0 },
  { symbol: "RKLBB", ticker: "RKLB", name: "Rocket Lab", address: "0xc8da12cbcce7c45180692a6420b0076e03a5179a", decimals: 18, priceImpactPct: 0 },
  { symbol: "SECZB", ticker: "SECZ", name: "Securitize", address: "0x32c980f38907ace4fac643c3765d9b32842af60f", decimals: 18, priceImpactPct: 0 },
  { symbol: "SHAZB", ticker: "SHAZ", name: "SharonAI", address: "0x0f31e21b7881f5583ea94ddbcb0bcaf22b1abeab", decimals: 18, priceImpactPct: 0 },
  { symbol: "SKHYB", ticker: "SKHY", name: "SK Hynix", address: "0xca750ef65f295bbecd685abf54e82caf297bdb61", decimals: 18, priceImpactPct: 0.001193196 },
  { symbol: "SMCIB", ticker: "SMCI", name: "Super Micro Computer, Inc.", address: "0x387dea1d2772d716d081a29116f3effa0ffe1f36", decimals: 18, priceImpactPct: 0 },
  { symbol: "SPCXB", ticker: "SPCX", name: "SpaceX", address: "0xbe9d156892e55e7154bcd3cb0fea677f9d3103e1", decimals: 18, priceImpactPct: 0 },
  { symbol: "SPYB", ticker: "SPY", name: "SPDR S&P 500 ETF Trust", address: "0x7138b48df7d98d7e3cc221bfe7192d0a178182d8", decimals: 18, priceImpactPct: 0.000100037 },
  { symbol: "STXB", ticker: "STX", name: "Seagate", address: "0x2e065f65f1699964f4092de1d39a8efe6c8d6f32", decimals: 18, priceImpactPct: 0 },
  { symbol: "TSLAB", ticker: "TSLA", name: "Tesla, Inc.", address: "0x5b1910eaad6450e50f816082aa078c41f10c292f", decimals: 18, priceImpactPct: 0.0005012544 },
  { symbol: "TSMB", ticker: "TSM", name: "Taiwan Semiconductor Manufacturing Co Ltd.", address: "0xab78b89b5bb00236be0b4b20704cbfa04efc711c", decimals: 18, priceImpactPct: 0 },
  { symbol: "USARB", ticker: "USAR", name: "USA Rare Earth, Inc.", address: "0xcd345d4450e04cdef422a60b97d9265d24e0bcee", decimals: 18, priceImpactPct: 0 },
  { symbol: "WDCB", ticker: "WDC", name: "Western Digital", address: "0xebe29695f8047c13d36e7a790ca8c1b239ffad1c", decimals: 18, priceImpactPct: 0 },
  { symbol: "WENB", ticker: "WEN", name: "Wendy's", address: "0xded1c5fb38c262beb9cff1e1116eff3c5bf278cd", decimals: 18, priceImpactPct: 0.0025021031 },
  { symbol: "ZMB", ticker: "ZM", name: "Zoom Communications", address: "0xf4ddb292fe88e476eddd9869d386705e6bfab7a2", decimals: 18, priceImpactPct: 0.0510678249 },
];
